import type { Pool } from "pg";
import { getPool } from "./db";

type Token = { token: string; expiresAt: number };
type Options = {
  pool: Pick<Pool, "connect" | "query">;
  issue: () => Promise<Token>;
  now?: () => number;
  wait?: (ms: number) => Promise<void>;
  lockWaitMs?: number;
};
const LOCK_ID = 36190601;
const COOLDOWN_MS = 65_000;

/** A dedicated connection owns the advisory lock until issuance and persistence finish. */
export function createTokenManager(options: Options) {
  const now = options.now ?? Date.now;
  const wait = options.wait ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));
  let pending: Promise<string> | undefined;
  let cached: Token | undefined;

  async function acquire(): Promise<string> {
    const client = await options.pool.connect();
    let locked = false;
    let releaseError: Error | undefined;
    const deadline = now() + (options.lockWaitMs ?? 15_000);
    try {
      do {
        const stored = await client.query("SELECT token, expires_at FROM kis_tokens WHERE id=1");
        const row = stored.rows[0];
        if (row?.token && new Date(row.expires_at).getTime() > now()) {
          cached = { token: row.token, expiresAt: new Date(row.expires_at).getTime() };
          return cached.token;
        }
        const lock = await client.query("SELECT pg_try_advisory_lock($1) AS locked", [LOCK_ID]);
        locked = lock.rows[0].locked;
        if (locked) break;
        if (now() >= deadline) throw new Error("KIS token issuance is busy; retry later");
        await wait(100);
      } while (!locked);

      // Another process may have refreshed between our first read and acquiring the lock.
      const stored = await client.query("SELECT token, expires_at, last_attempt_at FROM kis_tokens WHERE id=1");
      const row = stored.rows[0];
      if (row?.token && new Date(row.expires_at).getTime() > now()) {
        cached = { token: row.token, expiresAt: new Date(row.expires_at).getTime() };
        return cached.token;
      }
      if (row?.last_attempt_at && now() - new Date(row.last_attempt_at).getTime() < COOLDOWN_MS) {
        throw new Error("KIS token issuance cooldown; retry later");
      }
      // Autocommit before HTTP: failures and process death must not erase the cooldown.
      await client.query("INSERT INTO kis_tokens(id,last_attempt_at) VALUES(1,$1) ON CONFLICT(id) DO UPDATE SET last_attempt_at=EXCLUDED.last_attempt_at", [new Date(now())]);
      const token = await options.issue();
      await client.query("UPDATE kis_tokens SET token=$1,expires_at=$2 WHERE id=1", [token.token, new Date(token.expiresAt)]);
      cached = token;
      return token.token;
    } finally {
      if (locked) {
        try { await client.query("SELECT pg_advisory_unlock($1)", [LOCK_ID]); }
        catch { releaseError = new Error("Failed to release KIS token lock"); }
      }
      // Destroy a connection whose lock release failed; never return it to the pool.
      client.release(releaseError);
    }
  }

  return {
    async get(): Promise<string> {
      if (cached && cached.expiresAt > now()) return cached.token;
      if (!pending) pending = acquire().finally(() => { pending = undefined; });
      return pending;
    },
    async invalidate(rejectedToken: string): Promise<void> {
      if (cached?.token === rejectedToken) cached = undefined;
      // A late 401 must not delete a newer token generated by another worker.
      await options.pool.query("UPDATE kis_tokens SET token=NULL,expires_at=NULL WHERE id=1 AND token=$1", [rejectedToken]);
    },
  };
}

async function issueToken(): Promise<Token> {
  const response = await fetch(`${process.env.KIS_BASE_URL}/oauth2/tokenP`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ grant_type: "client_credentials", appkey: process.env.KIS_APP_KEY, appsecret: process.env.KIS_APP_SECRET }),
    signal: AbortSignal.timeout(10_000),
  });
  const data = await response.json().catch(() => null);
  if (!response.ok || typeof data?.access_token !== "string" || !Number.isFinite(data?.expires_in) || data.expires_in <= 0) {
    // Do not expose the upstream payload, which may contain credentials or account data.
    throw new Error(`KIS token issuance failed (HTTP ${response.status})`);
  }
  const margin = Math.min(3600, data.expires_in / 10);
  return { token: data.access_token, expiresAt: Date.now() + (data.expires_in - margin) * 1000 };
}

let manager: ReturnType<typeof createTokenManager> | undefined;
function tokenManager() {
  return manager ??= createTokenManager({ pool: getPool(), issue: issueToken });
}
export function getAccessToken() { return tokenManager().get(); }
export function invalidateToken(token: string) { return tokenManager().invalidate(token); }
